/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Canary Games (https://sketchfab.com/CapAlatriste)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/18-misfit-room-inktober2019-6e216a6f02da43d89c2bd818f7890319
Title: #18 Misfit Room - "Inktober2019"
*/

import React, { useRef, useState, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

 
export function Manicomio(props) {

  const { nodes, materials } = useGLTF("/assets/models/Scenarios/18_misfit_room_-_inktober2019.glb");

  return (
    <group {...props} dispose={null} position-z={-1} rotation-y={-Math.PI/1} position-y={-3} scale={[3.2, 3.8, 3]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Lights}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Misfit_Room2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Misfit_Room}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/Scenarios/18_misfit_room_-_inktober2019.glb");
export default Manicomio;