export const introArray = [
  {
    id: 1,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Alice Brown, una de las mejores científicas del país, ha destinado toda su vida al estudio de la física cuántica y los viajes en el tiempo.",
    message:
      "Alice Brown, one of the country's top scientists, has dedicated her entire life to the study of quantum physics and time travel.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 2,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Ha estado trabajando en un brazalete que le permitiría escoger la fecha a dónde quiere viajar en el pasado, sin embargo, este artefacto no tiene la energía suficiente para que funcione.",
    message:
      "She has been working on a bracelet that would allow her to choose the date to which she wants to travel into the past. However, this device does not have enough energy to function.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    animation: 0,
    sonido: 0,
  }, //brazalete
  {
    id: 3,
    imageUrl: "/assets/img/scenarios/car.png",
    mensaje:
      "Tenía su vida feliz con su hijo y su esposo, pero desafortunadamente, ella, su hijo y su esposo tuvieron un accidente automovilístico, y todos menos ella, perdieron la vida.",
    message:
      "She had a happy life with her son and husband, but unfortunately, she, her son, and her husband had a car accident, and everyone except her lost their lives.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: true,
    jonas: true,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    animation: 0,
    sonido: 0,
  }, //añadir modelosd e hijo y esposo
  {
    id: 4,
    imageUrl: "/assets/img/scenarios/car.png",
    mensaje:
      "Alice ha quedado devastada tras este hecho, pues prácticamente toda su vida se ha derrumbado.",
    message:
      "Alice has been devastated by this event, as practically her whole life has crumbled.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
  },
  {
    id: 5,
    imageUrl: "/assets/img/scenarios/car.png",
    mensaje:
      "Tras la tragedia, experimenta visiones perturbadoras que la hacen dudar su salud. A pesar de su empeño en usar el brazalete, comienza a perder la esperanza en su recuperación.",
    message:
      "After the tragedy, she experiences disturbing visions that make her doubt her health. Despite her efforts to use the bracelet, she begins to lose hope in her recovery.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
  },
  {
    id: 6,
    imageUrl: "/assets/img/scenarios/thundersorm.png",
    mensaje:
      "En una tarde lluviosa, cerca de su casa, Alice vio algo cerca a un viejo árbol, al ir a investigar, Fue alcanzada por un rayo.",
    message:
      "On a rainy afternoon near her house, Alice saw something near an old tree. When she went to investigate, she was struck by lightning.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
  },
  {
    id: 7,
    imageUrl: "/assets/img/scenarios/car.png",
    mensaje:
      "Tras el impacto del rayo, Alice,  momentáneamente aturdida y desconcertada, se apresura a casa para recuperarse.",
    message:
      "After the lightning strike, Alice, momentarily stunned and bewildered, rushes home to recover.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
  },
  {
    id: 8,
    imageUrl: "/assets/img/scenarios/car.png",
    mensaje:
      "Mientras se recuperaba en casa, el brazalete en su brazo se iluminó, llevándola a creer que podría viajar en el tiempo. Sin dudarlo, eligió su cumpleaños como su primera parada en su viaje temporal.",
    message:
      "While recovering at home, the bracelet on her arm lit up, leading her to believe she could time travel. Without hesitation, she chose her birthday as her first stop on her temporal journey.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
  },
  {
    id: 9,
    imageUrl: "/assets/img/scenarios/car.png",
    mensaje:
      "De repente, todo se oscureció, y cuando despertó, se encontró en su cuarto. Para su asombro, su esposo e hijo la sorprendieron en la mañana de su cumpleaños, vivos y llenos de alegría.",
    message:
      "Suddenly, everything went dark, and when she woke up, she found herself in her room. To her amazement, her husband and son surprised her on her birthday morning, alive and filled with joy.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
  },
  {
    id: 10,
    imageUrl: "/assets/img/scenarios/car.png",
    mensaje:
      "Alice disfrutó el día con su familia, aunque las preguntas la atormentaban. Decidió no pensar demasiado en ello y se sumergió en la felicidad de estar con ellos de nuevo.",
    message:
      "Alice enjoyed the day with her family, although questions tormented her. She chose not to dwell on them and immersed herself in the happiness of being with them again.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
  },
  {
    id: 11,
    imageUrl: "/assets/img/scenarios/car.png",
    mensaje:
      "Al despertar, volvió a su triste realidad original, confundida y abrumada por la tristeza. Se preguntaba si lo que vivió fue un sueño o si el brazalete tuvo un papel en ese extraño episodio.",
    message:
      "Upon waking, she returned to her original sad reality, confused and overwhelmed by sorrow. She wondered if what she had experienced was a dream or if the bracelet played a role in that strange episode.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
  },
  {
    id: 12,
    imageUrl: "/assets/img/scenarios/car.png",
    mensaje:
      "Después de despertar en su realidad original, un vecino golpeó su puerta preocupado por un rayo cercano y notó una quemadura en la mano de Alice. Le sugirió que fueran al hospital.",
    message:
      "After waking up in her original reality, a neighbor knocked on her door, concerned about a nearby lightning strike and noticed a burn on Alice's hand. He suggested they go to the hospital.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
  },
  {
    id: 13,
    imageUrl: "/assets/img/scenarios/car.png",
    mensaje:
      "¡Hola! Escuché un fuerte estruendo de un rayo y me preocupé. ¿Estás bien?",
    message: "Hello! I heard a loud thunder and got worried. Are you okay?",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
  },
  {
    id: 14,
    imageUrl: "/assets/img/scenarios/car.png",
    mensaje:
      "Sí, estoy bien, gracias por preocuparte. Fue un rayo cercano, pero estoy ilesa.",
    message:
      "Yes, I'm fine, thank you for caring. It was a nearby lightning strike, but I'm unharmed.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
  },
  {
    id: 15,
    imageUrl: "/assets/img/scenarios/car.png",
    mensaje:
      "Espera, ¿qué te pasó en la mano? ¿Estás segura de que estás bien?",
    message: "Wait, what happened to your hand? Are you sure you're okay?",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
  },
  {
    id: 16,
    imageUrl: "/assets/img/scenarios/car.png",
    mensaje:
      "No estoy segura de cómo ocurrió. De repente, estaba en mi cuarto y...",
    message: "I'm not sure how it happened. Suddenly, I was in my room and...",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
  },
  {
    id: 17,
    imageUrl: "/assets/img/scenarios/car.png",
    mensaje:
      "¿Te lastimaste cuando cayó el rayo? Deberías ir al hospital para que lo revisen.",
    message:
      "Did you get hurt when the lightning struck? You should go to the hospital to get it checked.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
  },
  {
    id: 18,
    imageUrl: "/assets/img/scenarios/car.png",
    mensaje: "No estoy segura de cómo ocurrió esto, pero...",
    message: "I'm not sure how this happened, but...",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
  },
  {
    id: 19,
    imageUrl: "/assets/img/scenarios/outside.png",
    mensaje: "¿Qué hago? ¿Voy o no voy?",
    message: "What should I do? Should I go or not?",
    decision1en: "Yes",
    decision2en: "No",
    decision1es: "Si",
    decision2es: "No",
    alice: true,
    alex: false,
    jonas: false,
    eyder: true,
    carl: false,
    jimmy: false,
    narrador: false,
    photo: "assets/img/gif/keyboard.gif",
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    animation: 1,
    sonido: 0,
  },
];
export const bifur1Array = [
  {
    id: 20,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "...creo que tienes razón. Es mejor asegurarse de que todo esté en orden.",
    message:
      "I think you're right. It's better to make sure everything is in order.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 21,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Bueno, no te preocupes. Puedo llevarte al hospital si lo necesitas. Es importante cuidar esa quemadura.",
    message:
      "Well, don't worry. I can take you to the hospital if you need to. It's important to take care of that burn.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 22,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Eso sería amable de tu parte, gracias. No entiendo lo que está sucediendo, pero creo que es lo mejor.",
    message:
      "That would be kind of you, thank you. I don't understand what's happening, but I think it's for the best.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 23,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "En el hospital Alice comenta toda la situación al médico y espera resultados después de unos análisis.",
    message:
      "Decides to go to the hospital: At the hospital, Alice explains the whole situation to the doctor and waits for the results after some tests.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 24,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Hemos revisado tus análisis y observaciones con problemas mentales y esquizofrenia debido al daño causado por el rayo.",
    message:
      "We have reviewed your analyses and observations, and it appears that you have mental health problems and schizophrenia due to the damage caused by the lightning.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 25,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "¿Esquizofrenia? ¿Estás seguro? ¿No es posible que todo esto sea solo un sueño, una ilusión? ¿Qué es real?",
    message:
      "Schizophrenia? Are you sure? Could this all just be a dream, an illusion? What's real?",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 26,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Entiendo que esto debe ser abrumador para ti, Alice. Pero los análisis y observaciones clínicas son concluyentes. Ahora te quiero hablar respecto a dos pastillas experimental, que son una opción que podría ayudarte a recuperar la estabilidad mental.",
    message:
      "I understand that this must be overwhelming for you, Alice. But the clinical analyses and observations are conclusive. Now, I want to talk to you about two experimental pills, which are an option that could help you regain mental stability.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 27,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje: "No estoy segura, Doctor Carl. ¿Qué tipo de pastillas son?",
    message:
      "Son pastillas seguras y ha ayudado a muchas personas en situaciones similares. Tienes que escoger entre la roja y la azul.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 28,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje: "¿Qué efecto tendrá en mí?",
    message: "What will be the effect on me?",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 29,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "No te preocupes, no te alejará de la realidad, pero podría ayudarte a sentirte más tranquila, al menos temporalmente.",
    message:
      "Don't worry, it won't take you away from reality, but it might help you feel calmer, at least temporarily.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 30,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje: "¿qué pasta debo tomar?",
    message: "Which pill should I take?",
    decision1en: "Blue",
    decision2en: "Red",
    decision1es: "Azul",
    decision2es: "Roja",
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
];
export const bifur11Array = [
  {
    id: 31,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Está bien, Doctor Carl, lo intentaré con la pasta azul. Necesito encontrar algo de paz.",
    message:
      "Alright, Doctor Carl, I'll give the blue pill a try. I need to find some peace.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 32,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Has tomado una decisión valiente, Alice. Verás que esto te ayudará a sentirte mejor.",
    message:
      "You've made a brave choice, Alice. You'll see that this will help you feel better.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 33,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      'Su salud mental "mejora", supera el trauma y logra grandes avances en su carrera como científica, ganando un premio Nobel.',
    message:
      'Her mental health "improves," she overcomes the trauma, and achieves significant breakthroughs in her scientific career, winning a Nobel Prize.',
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 34,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Carl, ¿cómo se encuentra nuestra paciente, Alice? ¿Ha experimentado algún cambio notable?",
    message:
      "Carl, how is our patient, Alice? Has she experienced any noticeable changes?",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 35,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Doctor Carl: (tranquilamente) La paciente se encuentra muy bien, Jimmy. La pastilla ha tenido un efecto positivo en su estado. Está mucho más tranquila.",
    message:
      "The patient is doing very well, Jimmy. The pill has had a positive effect on her condition. She's much calmer.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 36,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje: "Carl, ¿tomó Alice la pastilla azul que le ofrecimos?",
    message: "Carl, did Alice take the blue pill we offered?",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 37,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Sí, Jimmy, la tomó. Parece que estamos manteniéndola en la realidad fabricada.",
    message:
      "Yes, Jimmy, she took it. It seems we're keeping her in the fabricated reality.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
];
export const bifur12Array = [
  {
    id: 38,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Está bien, lo intentaré con la pasta roja. Necesito encontrar algo de paz.",
    message:
      "Alright, I'll give the red pill a try. I need to find some peace.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 39,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Has tomado una decisión valiente. Verás que esto te ayudará a sentirte mejor.",
    message:
      "You've made a brave decision. You'll see that this will help you feel better.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 40,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje: "Su condición empeora y entra en coma.",
    message: "Su condición empeora y entra en coma.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 41,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje: "Carl, ¿qué ha sucedido con la paciente?",
    message: "Carl, what happened to the patient?",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 42,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Está en coma, no se recuperará pronto. Se le tiene que administrar de la pastilla azul para que sea como si no hubiera pasado nada.",
    message:
      "She's in a coma, she won't recover anytime soon. We need to give her the blue pill so it's like nothing ever happened.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 43,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje: "Nadie puede salir de aquí, eh?",
    message: "Nobody can get out of here, huh?",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 44,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Se estaba haciendo muchas preguntas, teníamos que deshacernos de ella. Ambos ríen",
    message:
      "She was asking too many questions, we had to get rid of her. They both laugh.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
];
export const bifur2Array = [
  {
    id: 45,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Aprecio tu preocupación, pero en realidad estoy cansada y preferiría quedarme, además, la quemadura es pequeña. Gracias de todos modos.",
    message:
      "I appreciate your concern, but I am actually tired and would prefer to stay home, besides, the burn is small. Thank you anyway.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 46,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "En su casa, decide regresar al pasado una vez más para salvar a su familia. Va al día del accidente.",
    message:
      "At her home, she decides to return to the past once more to save her family. She goes to the day of the accident.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 47,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Se encontró su casa que recordaba y se sentía apresurada por encontrar a su esposo y a su hijo.",
    message:
      "She found her home that she remembered and felt rushed to find her husband and her son.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 48,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Buscó en todos los sitios de la casa y no los encontraba. Entonces decidió irse en su auto a buscarlos porque intuyó que ya se habían ido. Esta era mi última oportunidad de cambiar el curso de los eventos y salvarlos.",
    message:
      "She searched in all the places in the house and couldn't find them. Then she decided to leave in her car to look for them because she had a feeling they had already left. This was my last chance to change the course of events and save them.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 49,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje: "Una vez en el carro, no sabe por cuál camino ellos se fueron.",
    message: "Once in the car, she doesn't know which way they went.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 50,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje: "¿Por cuál calle debería ir? ¿Calle 1 o Calle 2?",
    message: "Which street should I go on? Street 1 or Street 2?",
    decision1en: "Street 1",
    decision2en: "Street 2",
    decision1es: "Calle 1",
    decision2es: "Calle 2",
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
];
export const bifur21Array = [
  {
    id: 51,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje: "¡Esperen!",
    message: "Wait!",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 52,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Alice ve frente a sus ojos cómo su familia pierde la vida en el accidente.",
    message:
      "Alice watches in horror as her family loses their lives in the accident.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 53,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Decide hacer otro viaje al pasado, y esta vez ella ya sabe cómo han ocurrido las cosas.",
    message:
      "She decides to make another trip to the past, and this time she already knows how things have happened.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 54,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Ella es la que se accidenta con aquel camión y muere, y su familia se salva.",
    message:
      "She is the one who has the accident with that truck and dies, and her family is saved.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 55,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Hombre misterioso toma el brazalete y desaparece en la oscuridad.",
    message:
      "The mysterious man takes the bracelet and disappears into the darkness.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
];
export const bifur22Array = [
  {
    id: 56,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Cerca del automóvil, Alice finalmente encuentra un momento a solas con su esposo, decidida a explicarle la extraña situación y, con suerte, evitar la tragedia que se avecina.",
    message:
      "Near the car, Alice finally finds a moment alone with her husband, determined to explain the strange situation and, hopefully, avert the impending tragedy.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 57,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Amor, por favor, necesito que me escuches. Lo que voy a decir puede sonar increíble, pero es de vital importancia.",
    message:
      "Honey, please, I need you to listen to me. What I'm about to say may sound unbelievable, but it's of vital importance.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 58,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "¿Qué pasa, Amor? Estás muy agitada, sabes que no podemos perder el viaje.",
    message:
      "What's going on, Love? You seem very agitated, you know we can't miss the trip.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 59,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Lo que voy a decir puede sonar extraño, pero esta mañana experimenté algo que no puedo explicar. He viajado en el tiempo, he visto el futuro. Y en ese futuro, tú y nuestro hijo... están en peligro.",
    message:
      "Alice: (speaking in a hushed voice) What I'm about to say may sound strange, but this morning I experienced something I can't explain. I traveled through time, I saw the future. And in that future, you and our son... are in danger.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 60,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje: "Alice, no entiendo. ¿De qué estás hablando?",
    message: "Alice, I don't understand. What are you talking about?",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 61,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "No tengo tiempo para explicarlo todo ahora, pero necesito que confíes en mí. Por favor, quédate con nuestra hijo aquí y evita que suba al automóvil. Yo lo manejaré. Es la única manera de mantenerlos a salvo.",
    message:
      "I don't have time to explain it all now, but I need you to trust me. Please, stay with our son here and prevent him from getting in the car. I'll drive it. It's the only way to keep you safe.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 62,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Alice, esto suena como una locura. Pero si esto es lo que necesitas, lo haré. Vamos a casa ♥.",
    message:
      "Alice, this sounds like madness. But if this is what you need, I'll do it. Let's go home ♥.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 63,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Alice logra salvar a su familia y regresa al presente original, donde su esposo e hijo están a salvo y bien. Aunque aún tiene esa sensación extraña.",
    message:
      "Alice manages to save her family and returns to the original present, where her husband and son are safe and well. Although she still has that strange feeling.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 64,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje: "Sin embargo, el vecino regresa para saber cómo sigue.",
    message: "However, the neighbor returns to check how you're doing.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 65,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje: "Hola Alice, cómo sigues?",
    message: "Hello Alice, how are you?",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 66,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje: "Todo muy bien, mi familia y yo estamos bien",
    message: "Everything's fine, my family and I are well.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 67,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje: "Perdón? Alice, tu familia murió hace dos años, estás sola aquí",
    message:
      "I'm sorry? Alice, your family died two years ago, you're alone here.",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 68,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje: "¿Estás segura que no quieres ir al médico?",
    message: "Are you sure you don't want to go to the doctor?",
    decision1en: "Go with the neighbor",
    decision2en: "Don't go with the neighbor",
    decision1es: "Ir con el vecino",
    decision2es: "No ir con el vecino",
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
];
export const bifur221Array = [
  {
    id: 69,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "No es cierto, mi familia está conmigo. No los veo, No entiendo nada...",
    message:
      "It's not true, my family is with me. I can't see them, I don't understand...",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 70,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje: "Alice es diagnosticada con esquizofrenia",
    message: "Alice is diagnosed with schizophrenia",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
];
export const bifur222Array = [
  {
    id: 71,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "No es cierto, mi familia está conmigo. No los veo, No entiendo nada...",
    message:
      "It's not true, my family is with me. I can't see them, I don't understand...",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 72,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Alice queda en blanco y, de repente, despierta del coma. Confundida en el hospital",
    message:
      "Alice goes blank and suddenly wakes up from the coma. Confused in the hospital",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
  {
    id: 73,
    imageUrl: "/assets/img/scenarios/laboratory.png",
    mensaje:
      "Alice descubre que hubo un accidente con su familia y que los demás murieron mientras ella se salvó. Todo el tiempo estuvo en coma y fue un sueño",
    message:
      "Alice discovers that there was an accident with her family and the others died while she was saved. She realizes that the whole time she was in a coma and it was a dream",
    decision1en: null,
    decision2en: null,
    decision1es: null,
    decision2es: null,
    alice: true,
    alex: false,
    jonas: false,
    eyder: false,
    carl: false,
    jimmy: false,
    narrador: false,
    animation: 0,
    id_scena: 1,
    rotationx: 0,
    rotationy: Math.PI / 2,
    rotationz: 0,
    positionx: 0,
    positiony: 0,
    positionz: 0,
    sonido: 0,
  },
];
