/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { PropertyBinding } from "three";

export function AliceParty(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/assets/models/Alice/AliceDress/AliceDressAnimations.glb");
  const { actions } = useAnimations(animations, group);
  const [rotationx, setRotationx] = useState(0);
  const [rotationz, setRotationz] = useState(0);
  const [rotationy, setRotationy] = useState(0);
  const [positionx, setPositionX] = useState(0);
  const [positiony, setPositionY] = useState(0);
  const [positionz, setPositionZ] = useState(0);
  const [scale, setScale] = useState(0)
  useEffect(() => {
    console.log(actions)
    for (const key in actions) {
      actions[key].fadeOut(0.5);
    }
    if(props.animation === 66){
      setPositionZ(-15)
      setPositionX(-2)
      setPositionY(0)
      setScale(5)
     // setRotationx( -Math.PI / 0.55)
      const action = actions["Dancing"];
      action.reset()
      .setEffectiveTimeScale( 1 )
      .setEffectiveWeight( 1 )
      .fadeIn(2)
      .play();
    }
    if((props.animation === 68) || (props.animation === 70) || (props.animation === 71) ){
      setPositionZ(0)
      setPositionX(-3)
      setPositionY(-5)
      setRotationy( Math.PI / 2)
      setScale(4)
      const action = actions["Idle"];
     action.reset()
     .setEffectiveTimeScale( 1 )
     .setEffectiveWeight( 1 )
     .fadeIn(2)
     .play();
    }
    if((props.animation === 69) || (props.animation === 21) || (props.animation === 25) || (props.animation === 23) ){
      setPositionZ(0)
      setPositionX(-3)
      setPositionY(-5)
      setRotationy( Math.PI / 2)
      setScale(4)
      const action = actions["Talking"];
     action.reset()
     .setEffectiveTimeScale( 1 )
     .setEffectiveWeight( 1 )
     .fadeIn(2 )
     .play();;
    }
    if((props.animation === 72)){
      setPositionZ(0)
      setPositionX(-3)
      setPositionY(-5)
      setRotationy( Math.PI * 2.2)
      const action = actions["Asking"];
      setScale(4)
     action.reset()
     .setEffectiveTimeScale( 1 )
     .setEffectiveWeight( 1 )
     .fadeIn( 0.5 )
     .play();
    }
    if(props.animation === 73){
      setPositionZ(0)
      setPositionX(-4)
      setPositionY(-5)
      setRotationy( Math.PI * 2.2)
      setScale(4)
      const action = actions["LookAround"];
     action.reset()
     .setEffectiveTimeScale( 1 )
     .setEffectiveWeight( 1 )
     .fadeIn( 0.5 )
     .play();
    }
    
  }, [props.animation]);
  return (
    <group ref={group} {...props} dispose={null} scale={scale}
    rotation-x={rotationx}
        rotation-z={rotationz}
        rotation-y={rotationy}
        position-x={positionx}
        position-z={positionz}
        position-y={positiony}
        >
      <group name="Scene">
        <group name="Armature">
          <skinnedMesh
            name="EyeLeft"
            geometry={nodes.EyeLeft.geometry}
            material={materials["Wolf3D_Eye.005"]}
            skeleton={nodes.EyeLeft.skeleton}
            morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
          />
          <skinnedMesh
            name="EyeRight"
            geometry={nodes.EyeRight.geometry}
            material={materials["Wolf3D_Eye.005"]}
            skeleton={nodes.EyeRight.skeleton}
            morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Body"
            geometry={nodes.Wolf3D_Body.geometry}
            material={materials["Wolf3D_Body.005"]}
            skeleton={nodes.Wolf3D_Body.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Glasses"
            geometry={nodes.Wolf3D_Glasses.geometry}
            material={materials["Wolf3D_Glasses.005"]}
            skeleton={nodes.Wolf3D_Glasses.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Hair"
            geometry={nodes.Wolf3D_Hair.geometry}
            material={materials["Wolf3D_Hair.005"]}
            skeleton={nodes.Wolf3D_Hair.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Head"
            geometry={nodes.Wolf3D_Head.geometry}
            material={materials["Wolf3D_Skin.005"]}
            skeleton={nodes.Wolf3D_Head.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Footwear"
            geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
            material={materials["Wolf3D_Outfit_Footwear.005"]}
            skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Top"
            geometry={nodes.Wolf3D_Outfit_Top.geometry}
            material={materials["Wolf3D_Outfit_Top.005"]}
            skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Teeth"
            geometry={nodes.Wolf3D_Teeth.geometry}
            material={materials["Wolf3D_Teeth.005"]}
            skeleton={nodes.Wolf3D_Teeth.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
          />
          <primitive object={nodes.Hips} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/Alice/AliceDress/AliceDressAnimations.glb");
export default AliceParty;

