/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ROY (https://sketchfab.com/roy.gearloft.in)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/road-sign-boards-and-grills-afb8ea31d6de45ea953a822b97ff9b04
Title: Road sign boards and grills
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Signs(props) {
  const { nodes, materials } = useGLTF("/assets/models/road_sign_boards_and_grills.glb");
  return (
    <group {...props} dispose={null} position-x={-5} position-y={0} position-z={-10} scale={6}>
      
      <group
        position={[0.34, 0.568, -0.057]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.036}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials["Material.006"]}
        />
      </group>
      </group>
  );
}

useGLTF.preload("/assets/models/road_sign_boards_and_grills.glb");
export default Signs