/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Miguel-Angel (https://sketchfab.com/Miguel-Angel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/road-intersection-896442019d0d401d91ed367c996954b2
Title: Road Intersection
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Street(props) {
  const { nodes, materials } = useGLTF("/assets/models/Scenarios/road_intersection.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={3.744}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.acera}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.pabimento}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/Scenarios/road_intersection.glb");
export default Street;

